version: "3.7"

services:

  django-face-recognition:
    build: ./
    container_name: django-face-recognition
    restart: always
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app

